version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.${APP_ENV}
    ports:
     - ${PORT}:3000
    volumes:
     - .:/app
     - ${YARN_CACHE_DIR}:/root/.yarn-cache
    environment:
     - NODE_ENV=${APP_ENV}
     - APP_ENV=${APP_ENV}
     - DEV_PORT=${PORT}